name = "cf-workers-status-poller"
workers_dev = true
main = "./dist/index.js"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

[triggers]
crons = ["*/3 * * * *"]
[observability.logs]
enabled = true

