name = "cf-workers-status-poller"
workers_dev = false
main = "./dist/index.js"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

[triggers]
crons = ["*/1 * * * *"]
[observability.logs]
enabled = true
[[services]]
binding = "UPTIMEFETCHER"
service = "uptimefetcher"
entrypoint = "UptimeFetcher"
 
[assets]
directory = "./dist/"
not_found_handling = "single-page-application"
binding = "ASSETS"
run_worker_first = [ "/api/*", "!/api/docs/*" ]

